# Generated by Django 4.2.8 on 2024-02-03 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_followships_userdetail_users_wallets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_address', models.CharField(max_length=100)),
                ('store', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('check_state', models.CharField(choices=[('0', '审核中'), ('1', '已审核')], default='0', max_length=1)),
                ('score_per', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_press', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('0', '书籍'), ('1', '服装'), ('2', '电子产品'), ('3', '食品'), ('4', '其他')], default='4', max_length=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'verbose_name': '商品详情',
                'verbose_name_plural': '商品详情',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
