# Generated by Django 4.2.8 on 2024-02-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '商品详情', 'verbose_name_plural': '商品详情'},
        ),
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_press',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('0', '书籍'), ('1', '服装'), ('2', '电子产品'), ('3', '食品'), ('4', '其他')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='score_per',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
