# Generated by Django 4.2.8 on 2024-02-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notices',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notices',
            name='notice_readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notices',
            name='notice_type',
            field=models.CharField(choices=[('1', '系统通知'), ('2', '关注商家上新'), ('3', '支付通知')], default='1', max_length=1),
        ),
    ]
