# Generated by Django 4.2.8 on 2024-02-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowShips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50)),
                ('buy_address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('0', '男'), ('1', '女')], default='0', max_length=1)),
                ('pay_type', models.CharField(choices=[('0', '支付宝'), ('1', '微信'), ('2', '银行卡')], default='0', max_length=1)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/')),
            ],
            options={
                'verbose_name': '用户详情',
                'verbose_name_plural': '用户详情',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('right', models.CharField(choices=[('0', '普通用户'), ('1', '管理员')], default='0', max_length=1)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name': '钱包',
                'verbose_name_plural': '钱包',
            },
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='followships',
            name='following_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user_id', to='users.users'),
        ),
        migrations.AddField(
            model_name='followships',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='users.users'),
        ),
    ]
