# Generated by Django 4.2.8 on 2024-02-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_followships_userdetail_users_wallets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='users',
            name='buy_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='pay_type',
            field=models.CharField(choices=[('0', '支付宝'), ('1', '微信'), ('2', '银行卡')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
